<?php

/**
 * @file
 * Ding Reservation Settings.
 *
 * Allows users to enable/disable quick reservation.
 */

/**
 * Implements hook_menu().
 */
function ding_reservation_settings_menu() {
  $items = array();

  $items['admin/config/ding/reservation_settings'] = array(
    'title' => 'Reservation settings',
    'description' => 'Configure reservation',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_reservation_settings_admin_form'),
    'file' => 'ding_reservation_settings.admin.inc',
    'access arguments' => array('admin config'),
  );

  return $items;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * Modifies user profile form.
 */
function ding_reservation_settings_form_profile2_edit_provider_fbs_form_alter(&$form, &$form_state, $form_id) {
  global $user;

  // Get user's "quick reservation" setting.
  $provider = ding_provider_get_provider_module_name('reservation');
  $profile = ding_user_provider_profile($user);
  $field_value = field_get_items('profile2', $profile, 'field_quick_reservation');
  $value = $field_value[0]['value'];

  ding_reservation_settings_field_settings($form, $provider, $value);

  array_unshift($form['#submit'], 'ding_reservation_settings_form_submit');
}

/**
 * Custom form submit for user edit form.
 *
 * @see ding_reservation_settings_form_profile2_edit_provider_fbs_form_alter()
 */
function ding_reservation_settings_form_submit($form, &$form_state) {
  $provider = ding_provider_get_provider_module_name('reservation');
  $values = &$form_state['values']['profile_provider_' . $provider];
  $quick_reservation = variable_get('ding_quick_reservation', FALSE);

  if ($quick_reservation == $values['field_quick_reservation'][LANGUAGE_NONE][0]['value']) {
    $values['field_' . $provider . '_interest_period'][LANGUAGE_NONE][0]['value'] = '';
    // Handle difference in field namings for different providers.
    if ($provider == 'openruth') {
      $values[$provider . '_preferred_branch'][LANGUAGE_NONE][0]['value'] = '_none';
    }
    else {
      $values['field_' . $provider . '_preferred_branch'][LANGUAGE_NONE][0]['value'] = '';
    }
  }
}

/**
 * Applies form config for quick reservation relate fields.
 *
 * @param array $form
 *   Form settings.
 * @param string $provider
 *   Provider identifier.
 * @param bool $user_quick_reservation
 *   Quick reservation value set by user.
 */
function ding_reservation_settings_field_settings(array &$form, $provider, $user_quick_reservation) {
  $quick_reservation = variable_get('ding_quick_reservation', FALSE);

  if ($quick_reservation) {
    $field_title = t('Disable quick reservation.');
    $field_desc = t('If you deactivate "quick"-reservation, you can choose pickup branch and interest period upon each reservation.');
  }
  else {
    $field_title = t('Enable quick reservation.');
    $field_desc = t('If you activate "quick"-reservation, you do not need to choose pickup branch and interest period upon each reservation.');
  }

  // Set field title.
  $form['profile_provider_' . $provider]['field_quick_reservation'][LANGUAGE_NONE]['#title'] = $field_title;
  // Set field description.
  $form['profile_provider_' . $provider]['field_quick_reservation'][LANGUAGE_NONE]['#description'] = $field_desc;

  $form['profile_provider_' . $provider]['field_' . $provider . '_interest_period']['#states'] = array(
    'disabled' => array(
      'input[name="profile_provider_alma[field_quick_reservation][und]"]' => array('checked' => (bool) $quick_reservation),
    ),
  );

  if ($provider == 'openruth') {
    $form['profile_provider_' . $provider][$provider . '_preferred_branch']['#states'] = array(
      'disabled' => array(
        'input[name="profile_provider_' . $provider . '[field_quick_reservation][und]"]' => array('checked' => (bool) $quick_reservation),
      ),
    );
  }
  else {
    $form['profile_provider_' . $provider]['field_' . $provider . '_preferred_branch']['#states'] = array(
      'disabled' => array(
        'input[name="profile_provider_' . $provider . '[field_quick_reservation][und]"]' => array('checked' => (bool) $quick_reservation),
      ),
    );
  }
}
