<?php

/**
 * @file
 * ding_reservation_settings.install
 */

/**
 * Implements hook_install().
 */
function ding_reservation_settings_install() {
  db_update('system')
    ->fields(array('weight' => 1000))
    ->condition('name', 'ding_reservation_settings', '=')
    ->execute();
}

/**
 * Implements hook_disable().
 */
function ding_reservation_settings_disable() {
  field_delete_field('field_quick_reservation');
}
